apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tesk-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: tesk-stack
  destination:
    namespace: tesk-stack
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:  
    - CreateNamespace=true 
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
    retry:
      limit: 50
      backoff: 
        duration: "60s"
        factor: 1
        maxDuration: "30m0s"
  source:
    repoURL: "harbor.federated-analytics.ac.uk/tesk/chart"
    chart: tesk-standalone-stack
    targetRevision: "0.0.0-pr.2"
    helm:
      valuesObject: 
        global:
          dev: false
          localDev: false
          kubeVersion: ""
          argoProject: tesk-stack
          namespace: tesk-stack
          argoNamespace: argocd
          ingress:
            enabled: true
            host: "localtest.me"
            className: "nginx"
            certClusterIssuer: "ca-issuer"

        networkPolicy:
          # ip not dns name
          egressMinioIP: ""

        prometheus:
          grafana:
            adminPassword: ""




        