apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-oci-harbor-stack
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  name: "harbor.feda tesk stack"
  type: helm
  url: harbor.federated-analytics.ac.uk/tesk/chart

