{{- if .Values.falco.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: {{ .Values.global.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    {{- include "tesk-standalone-stack.labels" . | nindent 4 }}
spec:
  project: {{ .Values.global.argoProject }}
  destination:
    namespace: {{ .Values.falco.namespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        # falco needs to run in a priv ns
        pod-security.kubernetes.io/enforce: privileged
        "admission.gatekeeper.sh/ignore": "pleaseignore"
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      refresh: true
  source:
    repoURL: {{ .Values.falco.repoURL }}
    chart: {{ .Values.falco.chart }}
    targetRevision: {{ .Values.falco.chartVersion }}
    helm:
      valuesObject:
        falco:
          webserver:
            prometheus_metrics_enabled: true

        metrics:
          enabled: true

        serviceMonitor:
          create: true

        falcosidekick:
          enabled: true
          replicaCount: 1

          config:
            talon:
              address: http://falco-talon:2803

          webui:
            enabled: true
            replicaCount: 1

            ingress:
              enabled: {{ .Values.global.ingress.enabled }}
              ingressClassName: {{ .Values.global.ingress.className }}
              hosts:
                - host: falcosidekick.{{ .Values.global.ingress.host }}
                  paths:
                    - path: /
              {{- if and (not .Values.global.dev) (not .Values.global.localDev) }}
              annotations:
                cert-manager.io/cluster-issuer: "{{ .Values.global.ingress.certClusterIssuer }}"
              tls:
              - hosts:
                - falcosidekick.{{ .Values.global.ingress.host }}
                secretName: falco-sidekick-cert
              {{- end }}

          serviceMonitor:
            enabled: true
          prometheusRules:
            enabled: true

          grafana:
            dashboards:
              enabled: true
              configMaps:
                falcosidekick:
                  name: falcosidekick-grafana-dashboard
                  namespace: "{{ .Values.prometheus.namespace }}"
                  folder: ""
                  folderAnnotation: grafana_dashboard_folder

        customRules:
          rules-detect-priv-esc.yaml: |
            - rule: Privilege escalation to root
              desc: Detect any attempt to switch to the root user within a container.
              condition: container and user.uid != 0 and proc.euid = 0 and evt.type = execve
              output: "Privilege escalation detected (user=%user.name uid=%user.uid container_id=%container.id command=%proc.cmdline)"
              priority: CRITICAL
        

{{- end }}